#!/usr/bin/env bash

set -e

bold=$(tput bold)
normal=$(tput sgr0)
green=`tput setaf 2`
nc=`tput sgr0`

repo="khulnasoft/kengine-cli"
output_tgz="/tmp/kengine.tar.gz"
dest_binary="/usr/local/bin"
os=$(uname | tr '[:upper:]' '[:lower:]')

echo "${bold}Downloading the Kengine CLI archive...${normal}"

latest_tag=$(curl --silent "https://api.github.com/repos/$repo/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')
version=$(echo $latest_tag | sed 's/^v//')

test -f $output_tgz && rm -f $output_tgz
curl -o $output_tgz -sOL "https://github.com/${repo}/releases/download/${latest_tag}/kengine-${os}-x64-v${version}.tar.gz"

echo "Extracting the kengine binary in $dest_binary"
rm -f "${dest_binary}/kengine"
tar -xzf $output_tgz -C $dest_binary
rm -f $output_tgz

echo -e "\n${green}âœ”${nc} kengine cli succesfully installed"
echo -e "\nWhat now?"
echo -e "# Run ${green}kengine login${nc} and become a kenginer!"