// make sure to add "kengine-api-key" to your Jenkins credentials prior to running this pipeline

pipeline {
    agent any

    stages {

        stage("Report") {

            // We need to specify our agent to be docker using Kengine image
            agent {
                docker {
                    image 'khulnasoft/kengine:latest'
                    args '--entrypoint='
                    reuseNode true
                }
            }

            environment {
                // Required: in order to authenticate with Kengine's API
                KENGINE_API_KEY = credentials('kengine-api-key')
            }

            steps {
                // This step will collect and print report of the alerts and their statuses for your service
                sh 'kengine report'
            }
        }
    }
}